### ISSUE TITLE
Key generation errors

### ISSUE THREAD

**Issue by blaxer** [Skylar-Tech/node-red-contrib-matrix-chat#11]
Getting the following error constantly repeating in the nodered logs, not sure what I can do to fix it.

generating oneTimeKeys,
generating fallback key,
Error uploading one-time keys TypeError: account.generate_fallback_key is not a function,
    at /data/node_modules/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:462:15,
    at /data/node_modules/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:250:7,
    at LocalStorageCryptoStore.getAccount (/data/node_modules/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/store/localStorage-crypto-store.js:348:5),
    at OlmDevice._getAccount (/data/node_modules/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:245:21),
    at /data/node_modules/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:461:10,
    at LocalStorageCryptoStore.doTxn (/data/node_modules/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/store/localStorage-crypto-store.js:374:28),
    at OlmDevice.generateFallbackKey (/data/node_modules/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:460:27),
    at uploadLoop (/data/node_modules/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/index.js:1728:32),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by skylord123** [comment]
This is interesting. Did you use an existing user or create a new one?

**Comment by skylord123** [comment]
I just wanted to update and say that there is known issues with using an existing account (that already has e2ee keys). Check this out for more information:
https://github.com/Skylar-Tech/node-red-contrib-matrix-chat#end-to-end-encryption-notes

I'm curious if you are using an existing account and that is what caused this error. I've tried a few things and can't seem to replicate this.

**Comment by blaxer** [comment]
Yes I was using an existing user that had keys already. I "fixed" the problem by creating a brand new user and just to keep things simple did not enable encryption on any rooms and that seemed to work fine.

**Comment by skylord123** [comment]
@blaxer I just released `0.3.0` that comes with a newer version of `matrix-js-sdk`. I'm hoping the newer release fixes this problem for you.

**Comment by skylord123** [comment]
Closing this as there has been no activity in a while.
