### ISSUE TITLE
Device Verification

### ISSUE THREAD

**Issue by skylord123** [Skylar-Tech/node-red-contrib-matrix-chat#124]
There is a thread on the matrix chat channel that we discussed this quite a bit. It has the latest info on the state of this feature:
https://matrix.to/#/!ppQOFZPDOZdYkxhyRo:skylar.tech/$LpIQ9XmTe0VVj9TThKwLHqwfKbrAwfSdamXLTQOdkhk?via=skylar.tech&via=matrix.org&via=chat.rios.org.br

There is a branch called `e2ee-wip` that I have been working on this feature under. It's at a point where you can get two clients to verify each other but it throws this weird error trying to upload the keys to the server:

```
15 Apr 18:29:07 - [warn] [matrix-device-verification:5f9cd93bd4d1fab5] Device verification cancelled Error: Key upload failed
{"failures":{"@skylord123:skylar.tech":{"<removed>":{"status":404,"errcode":"M_NOT_FOUND","message":"404: No user_signing key found for @testaccount:skylar.tech"}}}}
[Verification Start] verify() error KeySignatureUploadError: Key upload failed
    at upload (/home/skylar/Projects/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/index.js:1986:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Crypto.setDeviceVerification (/home/skylar/Projects/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/index.js:1991:11)
    at async SAS.verifyKeys (/home/skylar/Projects/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/verification/Base.js:336:7)
    at async SAS.checkMAC (/home/skylar/Projects/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/verification/SAS.js:457:5)
    at async SAS.verifyAndCheckMAC (/home/skylar/Projects/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/verification/SAS.js:335:5)
    at async SAS.doSendVerification (/home/skylar/Projects/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/verification/SAS.js:386:7)
    at async SAS.doVerification (/home/skylar/Projects/node-red-contrib-matrix-chat/node_modules/matrix-js-sdk/lib/crypto/verification/SAS.js:266:20) {
  value: { failures: { '@skylord123:skylar.tech': [Object] } }
}
```

Despite that error though both clients show the other as verified.

Before we fix this though we need to get matrix-js-sdk dependency updated to the latest. On the latest release they have deprecated libolm in favor of rust crypto which is being tracked under #122

**Comment by skylord123** [comment]
I rebased `e2ee-wip` off of `dev` so it has the latest.

**Comment by skylord123** [comment]
Landed in v1.0.0. The two nodes are now **`matrix-verification`** (event source — emits incoming requests and phase changes, with on-node filters for phase, initiated-by, type, self-verification, user allowlist, and room) and **`matrix-verification-action`** (request / accept / start SAS / confirm / mismatch / cancel). They're built on the Rust crypto stack from #122, so the libolm-era *"no user_signing key found"* key-upload error from the `e2ee-wip` branch is gone.

There's also a non-flow path on the server config node: a **Pending verification requests** button that lists incoming requests and walks you through the SAS (emoji) check interactively, plus **Set up secure backup & cross-signing** and **Manage sessions** views — so you can verify devices without building a flow at all.

@vampywiz17 — to your question: yes, this is in v1.0.0. A beta is published, please give it a try:

```
npm install node-red-contrib-matrix-chat@beta
```

Full changelog and PR: #142. Release notes: https://github.com/Skylar-Tech/node-red-contrib-matrix-chat/releases/tag/v1.0.0-beta.1. Closes when the stable v1.0.0 ships.
